version: '{build}'
max_jobs: 1
image: WMF 5
clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # au job parameters
  au_timeout: 100
  au_threads: 10
  au_push: true
  au_force: false

  # Github credentials - used to save result to gist and to commit pushed packages to the git repository
  github_user: caskater4
  github_pass:
    secure: 7FOJIa5NeU3qLOfUf0v13PkS3stxEXovBKuWsMtfA34sfDQOoKqvxwUpAtiUABoReNRqPQGQq68c7uoofmwwoeJnXuN2sD3oVv38s5MoO8x5gqFUX+VChgRjBGhaIxcyUYl0LYQs6uQC/+TZ7rf6qgyQsoNKkizl1QoTdY+b4IqWozoUEUsZKwQIBLaC21R31fgoy11cAB/kvLrbt7ooDYC8MggZVi7Z4s8GvnK3HiHqsH9r7WvmuwRkP3h0t5onMkeLlfnmpkC6N7e34297F0XS+BrYENfIYLPiEfMnxtqZehUyNCtCmgxUl70n0pwEe7PfZvv+dDz3fT+kVnvV0q5Bl6baN2SFn06ufOt1xOVzbgsLQGgSWaKXz5KuLnZ2HIo+ivxuF5HYY+XDvnY9hZP/xc7bfurjng8ibmfSJE37e4xvBdPvK4gnhZO6lpM4Dw/8huciZ98jUu1af6d084e+wZ8AwSEwTxIU/+b89b63OBdBCCg+oVk0g8p5fJ7MgFvrW9nmTAW2IlIkawCaxeaN177mSIz1hBH5TFhKFyLGs6JUlvpi5mdGT/pE4v034QhuOkLGx3LPcjwzO0vAc8epT9iUZCDZOP9X3n4g/QOmO8Ed/pOYTEk7akB0j0g/sAgWQu0W7/9gCg8WqE5ITfWVlkDHTTcIh/mZX+z9xutgjQTF/IP19u+gFDOONQZQnpDu6z4BPLSLdpmkEJM6YvE+4dLkMUcmJawDy4SQp9XlvD16ltHrzL6JzrsxRgtiP/ZA1dhDx19u+bMmyNqtjC8aU1sYdIOd0OEB1ZJbUieO6Ici+JBgszeT8QWABLX4EvmrcuUZlLpd80UE+so9gTF3aBqWIDm8w0DEGZFyMwIqwNGKZI2vY8aYGChq9C7NnKupC8PjQSx667LJcO+3wYiNepQGlsHaUDVA9Zjdk977+WmWIFOWFTKLZyVS5dlzdw/fI7LhwDEbMsSr56+VHw3QUuUaCPBU1WmtjxRIiN5XqXtJ1+RqxB0eV6tMnklZUmy7MUtn8ubrfW/sOLNd/iTa3jKVskhcJTLowaD6kOOyJMKx7wWgQzWx29b3SvC8TV9ZJJBGHtGCPXOZ/TQTOsj1ZirPEQsFXe9i+JE2kPAJCfzFewK95J6LJpYAwm6YlKoJ/dRoNpGEgamNJHKzc6S7tHUkTRqzomFVmWkYYBZ/11EKoQSARxMtBwO7X/uQr4gLqg7TLUuJipSE3wYETjMYhqnOsQAdm6c8DIvLRn7IO+lng+j2TFnD0UAxlQbPyQuxn4ZHtcmKtOUSdCFTgKNVF2gKVQ8KWpKO7YEzIoOoB5UueaeUB4KNQXwwWq9DgV4iPpendasJil7yLN7JiYmfm+7Q7Vdav49nh/xcNLzLA3aAjiJX81Cogwb+yKHuVCJXQwQwYfy06pKiEVkdc+d3jXmClCrEfYPQDlgz7x27KXWXpSs7Cn2feMrqcc7zIxmqL7NRG+LIDjJUqvlZnxFOi6RrGxkG9JwXGkiDqcHs+kbaAv/TmH6QzvtcbZmtn43olsmuPaDc9TlvYMOZ575aJdS7lXTJNQQlnW+hXYAAPSjufEDVXENaMoVrnQnhBrUNyUA6JV4qrdIBc8c0XXj088TgbLNshZnwCBVzDuyk+jiiwjlJVIJmJvSBHBC3VR1okpIF79NIVPhlJCgKHr1LaIirAGOXyvo7E0J2VaolZWeKVCHYadah/GRgL+5rSeoCS0/MJLWMJ6hMi7BCmg9NBzVK5QZ+g54M7QJD5O7SFn8i+Nl4BiaT4zQJVJ2JrsRMZAWJcHiZjxNb1aLXpS3Kp776AhdAEFpV1LMWPNaVpkHm7nVXI1ussAGm9ra4NsiDMqGUYqEh6135M/KP4hx18BCKMAQWJuEdMUkuMYz8oXRQ2Ebl7IMshbh5XYXd6rDcxjdjcbdZcZNeBbvodCYfxr5c/7BuPeOLjQeyfQth7aN7fkP46FkbghEMFwD6LmRqpwlj8rgT7dpgI6UIOoqbFs9c+L0yYNwrdEc1cuzH/410IHtBigYbbkIHnCPMxbCqm2I+3j2C+Ejsg4JdwScffPWyXSKB88FGw3AczHsu4fMzSaXq2JAEyV0qgdvMB1MFm1IjiScmeODI133SysPejVU+w9ylZNmk0xBS4FL4pNVNgRFsiHNw4xmhoq6Ys+EmE8r1XQn6M99XxDUqZhY4FfpgqtoRbv8Fn6/NZjoRYDAiKpPRSM6aDTawXGpjvYrN77OW2rxOWF4rXlsKWWxJAXNkMG64rSwmNuJxB6d13ilUKx3xF6Gu8liIybSUtql/Yn2qMSPpr3ZR28n3iQjDJaFmwccXAFasSmOEzW/xni434EfX5Y1Q0CmtjXieLSsrsIMeTX/d56f+AHMmZBOZ1Ax6jP3ebf2uJ2ss86yNN9V3ZAE18sIu5CUcofR3c9K8nH+Ql2Dm8m/KCfgCZ4jqHxxrGRkPnFhxOf/hrnl+qo0MMg3IO6h8mKQMjDNaSPuxc39JmWxTHgQHULrkzKXDEFtG4oE08m97nJLIOYyB87EKjp59rDh0QMg9sKXjRyRIOD4gXKCxpofvzT/u3D9ZH7xNACblpqgkKZ8Kt0J7s7k4v1SXzSSk/SXxAtyXCYLrsfdEmwJdrbLo0jvwtG4oelAr5xrm5YB1l5dd9TB/UqMhjzc1IbIXIfYXTCq79OW4Ittxt/jl2mZOex5E2/Rygd5+RmPeZsW4lcXuPaMvaC2IHIF3djBmr2u0uhodPJUiCQZvjTdAoi9EsVRxN0Jj06RXTO8v3k7FgF5Ie6mH2kW9TEfKF+lmzaF+X1zFArLT+HX5sbjhsPGa8ccdgZioEN4e562VlGlLQ4WXjpx2hZ3t6VkTf3x7OLNQygswV+HSX21dN1ZvTm/NnxA/umYZbqqvAnLEejwQ4KQv1xkYDAdaDB7En7bxYKR6Aof5XYqNWUFH9oAxZLtcz9BlFHZ6kS/ELj2dTHD2OKphZF/Qst+wAYiPDfPLyY2C8QcFGfj+O7ZrjyWcqA6B479yMiusrJrXAGS6VCitL8od9pegPGYigrpcqjhmlQDF1L8JB9VXdrAJJtKxOz6nl9791lZGe8FXdtuhQ+jBlo/+YoWjZ5XImLirgSg2irqcKznKxdQNXYi+cwtep8XTxFdhfhme/l/uQm7Ol6VAJv7pgRioYbMJ7bxXKTQayP+QoL9T8qd9ydVwLuE1WINJbrpUDmbcHyy1n9l0tP27y2I/8HtOTvVVt4Mp962Im5HyOFJdIWjrbyULNe8YuvH9UUuHiZLW49n++DWfxwlwGaXwEBXRdYlKekZXMvLuyU/uaBJo0duDq3ZFfPnGsigYP+2yUxeu67pmlHkmf8duj6+hfS+DbvX9u0JedhDq1rN5eczKRcxCtybZdRKP+R3EEGdrZx/9DPWjqS3NvI81TM1ttftXbHWfthgCtnoDO2ydkrSV5PqXd3MPTT766HR/6LzklTpezU+Tp0dVrbPI3Y8jcoW4fd6BNiU0KXnXdh3eCk5e0LAsRDhA40SXXwaAZZkkBOnkxEOsEQxAiJqsZwAj40Ev/PPA1JEu4qsegT/Gk/6M7Mw9rc2DmL+lUJQLVv09mBIS2s18xRuaMV2N5u66Esa6KyGV1BY39x2FBs80Jb6/gZsVySW4U27vpCOS2NxlCF0x7niZqgImGHZZi+C9ThPqq0CI/Rnp1pwWr217dPZEioYAQxNdil9y9pg559QX+tbczmW8uUo6zU0trzZlpKLfcxuxaY/pR21GJQS/p1XiSuoqnagYS6vQlM9+/cU8sTUdqOqmLidNfOkXrez2w1H4YR/Ag7y4y4RZmyyJ6Ajw2S+rJ2chJEz20pQ0QOtG8Vr4Y/TqkDO+jKdVknTjrLkPTHXRd8sSBf2I8dTQFcf6QeyTKKai1PKFe+SPG7uTZAIA4PVnC9GJl4x9g+Upbp4HghD1sbDI3yNSTUMDAnDnp9wYAZvZE/oiUDWQLFwuwR9wu3m8WHa4qUTDGbCymhTCgy27goa5HiqhydY2C3yPicCO4TfOz0BgOlwN/DsDx+lK5Vn8Lhv9LDbujI9FK8iKysRLTxYwdWCnZA6MX+3VsttGfPpz3KWzEaH9VNVyywrcUWr1Qfjr+Zv26a1R1vSAO6Fa669C3qWpbVincOK3U7SGDX7OFlf+vgryxabjTuy/yLKRzY0rzJQo42usM1UmOF9x0Zw+9WqEQpOGH9WKLLnRUTLURpsP5DIfhBduhFwN+9+dxnaFCUjJXLmnEJUck2MnZJWqRpnRpXK2hspUfEPocxBMl1gf7N0Ffb2/gPmsjnIbupSGfBalHnQiIWc=
  github_user_repo: 'caskater4/chocolatey-packages' #https://github.com/chocolatey/chocolatey-packages-template is 'chocolatey/chocolatey-packages-template'

  # Email credentials - for error notifications
  mail_user:
    secure: /uWprUr9Dvi0kroGju3w4FLXqq/ec4JgAGQacpdV7Gg=
  mail_pass:
    secure: 88eP5u/fvdq8YhorwOOGzQugAsiyaflR4gdJE8Mkb/A=
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the github_user (secret or not) and grab the id - https://gist.github.com/name/id
  gist_id:
    secure: zV5dss2VE5c351P1L1Kd5TU8RR8YTe1ozaO/a0yz0IhA/RRRFRtjbR6WhixlFz1j

  # Chocolatey API key - to push updated packages
  api_key:
    secure: dCdYrcQjxlAkl2sAjMRVC1LmD0OYiltqG2X/hbophOxJ3CX5S/Zy6/iG7xrzCYxI

init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey"

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- SET PATH=C:\Ruby21-x64\bin;%PATH%
- ruby -v
- gem install gist --no-ri --no-rdoc
- "ruby -e \"require 'gist'; Gist.login! username: ENV['github_user'], password: ENV['github_pass'] if ENV['github_user'] \""
- ps: |
    "machine github.com", "login $Env:github_user", "password $Env:github_pass" | Out-File ~/_netrc -Encoding ascii
    Install-PackageProvider -Name NuGet -Force
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
    Install-Module au -Scope CurrentUser
    Get-Module au -ListAvailable | select Name, Version

build_script:
- ps: .\au\update_all.ps1

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: gist.md

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
